#!/usr/bin/env python3
import re
import os

def main():
    theme_path = os.path.expanduser("~/.config/theme/theme.css")
    output_path = os.path.expanduser("~/.config/lazygit/colors.yml")

    if not os.path.exists(theme_path):
        print(f"Error: {theme_path} not found")
        return

    with open(theme_path, 'r') as f:
        content = f.read()

    colors = {}
    matches = re.findall(r'@define-color\s+(chrysaki-[\w-]+)\s+(#[0-9a-fA-F]{6,8});', content)
    for name, color in matches:
        colors[name] = color

    if not colors:
        print("No colors found in theme.css")
        return

    def get(name, fallback="#000000"):
        return colors.get(f"chrysaki-{name}", fallback)

    output = f"""# Lazygit color theme — Chrysaki palette
# Auto-generated by lazygit/scripts/update_colors.py
# Do not edit manually; run generate_and_apply_palette.sh to regenerate

gui:
  theme:
    activeBorderColor:
      - "{get('emerald-light', '#1a8a6a')}"   # Emerald Lt
      - "bold"
    inactiveBorderColor:
      - "{get('border', '#363a4f')}"  # Border
    searchingActiveBorderColor:
      - "{get('blonde', '#FBB13C')}"   # Blonde
      - "bold"
    optionsTextColor:
      - "{get('teal-light', '#20969c')}"  # Teal Lt
    selectedLineBgColor:
      - "{get('raised', '#252836')}"   # Raised
    inactiveViewSelectedLineBgColor:
      - "{get('surface', '#1c1f2b')}"  # Surface
    cherryPickedCommitBgColor:
      - "{get('amethyst-dim', '#1e1040')}"  # Amethyst Dim
    cherryPickedCommitFgColor:
      - "{get('amethyst-light', '#583090')}"   # Amethyst Lt
    markedBaseCommitBgColor:
      - "{get('teal-dim', '#0f4f54')}"  # Teal Dim
    markedBaseCommitFgColor:
      - "{get('teal-light', '#20969c')}"  # Teal Lt
    unstagedChangesColor:
      - "{get('blonde', '#FBB13C')}"   # Blonde
    defaultFgColor:
      - "{get('text-primary', '#e0e2ea')}"  # Primary Text
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(output)

    print(f"Updated {output_path}")

if __name__ == "__main__":
    main()
