#!/usr/bin/env python3
import re
import os

def main():
    theme_path = os.path.expanduser("~/.config/theme/theme.css")
    output_path = os.path.expanduser("~/.config/lazygit/colors.yml")

    if not os.path.exists(theme_path):
        print(f"Error: {theme_path} not found")
        return

    with open(theme_path, 'r') as f:
        content = f.read()

    colors = {}
    matches = re.findall(r'@define-color\s+(color-\d+)\s+(#[0-9a-fA-F]{6,8});', content)
    for name, color in matches:
        colors[name] = color

    if not colors:
        print("No colors found in theme.css")
        return

    def get_color(idx, fallback="#000000"):
        return colors.get(f"color-{idx}", fallback)

    # Map Chrysaki indexed colors → lazygit theme keys
    # Indices match palette.css role comments
    output = f"""# Lazygit color theme — Chrysaki palette
# Auto-generated by lazygit/scripts/update_colors.py
# Do not edit manually; run generate_and_apply_palette.sh to regenerate

gui:
  theme:
    activeBorderColor:
      - "{get_color(9, '#1a8a6a')}"   # Emerald Lt
      - "bold"
    inactiveBorderColor:
      - "{get_color(13, '#363a4f')}"  # Border
    searchingActiveBorderColor:
      - "{get_color(4, '#FBB13C')}"   # Blonde
      - "bold"
    optionsTextColor:
      - "{get_color(20, '#20969c')}"  # Teal Lt
    selectedLineBgColor:
      - "{get_color(1, '#252836')}"   # Raised
    inactiveViewSelectedLineBgColor:
      - "{get_color(11, '#1c1f2b')}"  # Surface
    cherryPickedCommitBgColor:
      - "{get_color(16, '#1e1040')}"  # Amethyst Dim
    cherryPickedCommitFgColor:
      - "{get_color(7, '#583090')}"   # Amethyst Lt
    markedBaseCommitBgColor:
      - "{get_color(17, '#0f4f54')}"  # Teal Dim
    markedBaseCommitFgColor:
      - "{get_color(20, '#20969c')}"  # Teal Lt — Royal Blue is too dark to read
    unstagedChangesColor:
      - "{get_color(4, '#FBB13C')}"   # Blonde
    defaultFgColor:
      - "{get_color(22, '#e0e2ea')}"  # Primary Text
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(output)

    print(f"Updated {output_path}")

if __name__ == "__main__":
    main()
