#!/usr/bin/env python3
"""Generate theme.css from the pinned chrysaki-core JSON artifact.

Default source: chrysaki/core/chrysaki.json
Legacy SCSS input remains accepted as the first CLI argument for rollback.
Output: ~/.config/theme/theme.css with @define-color chrysaki-<name> + text colors.
"""
import json
import re
import os
import sys

FALLBACK_BLACK = "#2E3138"
FALLBACK_WHITE = "#FFF8F0"
CONTRAST_THRESHOLD = 4.5

# Known supplemental colors not in _palette.scss but part of Chrysaki spec
SUPPLEMENTAL = {
    "error-light": "#b53f4a",
    "error-dim": "#5e1f25",
}


def hex_to_rgb(hex_color):
    h = hex_color.lstrip("#")
    if len(h) == 8:
        h = h[:6]
    return tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))


def luminance(r, g, b):
    vals = []
    for x in (r, g, b):
        s = x / 255.0
        vals.append(((s + 0.055) / 1.055) ** 2.4 if s > 0.03928 else s / 12.92)
    return 0.2126 * vals[0] + 0.7152 * vals[1] + 0.0722 * vals[2]


def contrast(rgb1, rgb2):
    l1 = luminance(*rgb1)
    l2 = luminance(*rgb2)
    bright = max(l1, l2)
    dark = min(l1, l2)
    return (bright + 0.05) / (dark + 0.05)


def get_best_text_color(bg_hex, darkest, lightest):
    try:
        bg = hex_to_rgb(bg_hex)
        dk = hex_to_rgb(darkest)
        lt = hex_to_rgb(lightest)
        fb = hex_to_rgb(FALLBACK_BLACK)
        fw = hex_to_rgb(FALLBACK_WHITE)
    except Exception:
        return FALLBACK_WHITE

    max_dark = max(contrast(bg, dk), contrast(bg, fb))
    max_light = max(contrast(bg, lt), contrast(bg, fw))

    if max_light > max_dark:
        return lightest if contrast(bg, lt) >= CONTRAST_THRESHOLD else FALLBACK_WHITE
    else:
        return darkest if contrast(bg, dk) >= CONTRAST_THRESHOLD else FALLBACK_BLACK


def get_palette_extremes(colors):
    valid = []
    for hex_val in colors.values():
        try:
            rgb = hex_to_rgb(hex_val)
            lum = luminance(*rgb)
            valid.append((hex_val, lum))
        except Exception:
            continue
    if not valid:
        return FALLBACK_BLACK, FALLBACK_WHITE
    valid.sort(key=lambda x: x[1])
    return valid[0][0], valid[-1][0]


def parse_scss(scss_path):
    """Parse SCSS $name: #HEX; and $name: $other; declarations."""
    raw = {}
    with open(scss_path, "r") as f:
        for line in f:
            m = re.match(r"\s*\$(\S+)\s*:\s*(.+?)\s*;", line)
            if m:
                raw[m.group(1)] = m.group(2).strip()
    return raw


def resolve_scss(raw):
    """Resolve SCSS aliases ($warning: $blonde) to hex values, supporting multi-hop."""
    resolved = {}
    MAX_DEPTH = 10
    for name, value in raw.items():
        v = value
        depth = 0
        while v.startswith("$") and depth < MAX_DEPTH:
            ref = v.lstrip("$")
            if ref not in raw:
                break
            v = raw[ref]
            depth += 1
        if v.startswith("#"):
            resolved[name] = v
    # Add supplemental colors
    for name, hex_val in SUPPLEMENTAL.items():
        if name not in resolved:
            resolved[name] = hex_val
    return resolved


def parse_core_json(json_path):
    """Read the resolved token contract emitted by chrysaki-core."""
    with open(json_path, "r") as f:
        document = json.load(f)
    colors = document.get("tokens")
    if not isinstance(colors, dict):
        raise ValueError(f"{json_path}: expected an object at tokens")
    invalid = [name for name, value in colors.items() if not re.fullmatch(r"#[0-9a-fA-F]{6}", value)]
    if invalid:
        raise ValueError(f"{json_path}: invalid resolved tokens: {', '.join(invalid)}")
    return colors


def generate_theme_css(colors):
    darkest, lightest = get_palette_extremes(colors)
    lines = [
        "/* Chrysaki theme — auto-generated by generate_theme_css.py */",
        "/* Source: pinned chrysaki/core/chrysaki.json */",
        "/* Do not edit manually; run theme/scripts/generate_theme_css.py to regenerate */",
        "",
    ]

    # Emit named tokens: @define-color chrysaki-<name> #HEX;
    for name, hex_val in sorted(colors.items()):
        text_color = get_best_text_color(hex_val, darkest, lightest)
        lines.append(f"@define-color chrysaki-{name} {hex_val};")
        lines.append(f"@define-color text-chrysaki-{name} {text_color};")
    lines.append("")

    return "\n".join(lines)


def main():
    source_path = os.path.expanduser("~/dots/chrysaki/core/chrysaki.json")
    output_path = os.path.expanduser("~/.config/theme/theme.css")

    if len(sys.argv) > 1:
        source_path = os.path.expanduser(sys.argv[1])
    if len(sys.argv) > 2:
        output_path = os.path.expanduser(sys.argv[2])

    if not os.path.exists(source_path):
        print(f"Error: {source_path} not found", file=sys.stderr)
        sys.exit(1)

    try:
        if source_path.lower().endswith(".json"):
            colors = parse_core_json(source_path)
        else:
            colors = resolve_scss(parse_scss(source_path))
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Error: {error}", file=sys.stderr)
        sys.exit(1)

    if not colors:
        print("Error: No colors found in palette source", file=sys.stderr)
        sys.exit(1)

    css = generate_theme_css(colors)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(css)

    print(f"Generated {output_path} ({len(colors)} colors)")


if __name__ == "__main__":
    main()
