#!/usr/bin/env python3
"""Bridge script: reads Chrysaki _palette.scss → generates theme.css with named tokens.

Single source of truth: chrysaki/ags/.config/ags/styles/_palette.scss
Output: ~/.config/theme/theme.css with @define-color chrysaki-<name> + text colors.
"""
import re
import os
import sys

FALLBACK_BLACK = "#2E3138"
FALLBACK_WHITE = "#FFF8F0"
CONTRAST_THRESHOLD = 4.5

# Known supplemental colors not in _palette.scss but part of Chrysaki spec
SUPPLEMENTAL = {
    "error-light": "#b53f4a",
    "error-dim": "#5e1f25",
}

# Legacy index → named token mapping (for backward compat during migration)
LEGACY_INDEX_MAP = [
    "base",           # 0
    "raised",         # 1
    "teal",           # 2
    "emerald",        # 3
    "blonde",         # 4
    "blue",           # 5
    "amethyst",       # 6
    "amethyst-light", # 7
    "error",          # 8
    "emerald-light",  # 9
    "abyss",          # 10
    "surface",        # 11
    "elevated",       # 12
    "border",         # 13
    "blue-light",     # 14
    "emerald-dim",    # 15
    "amethyst-dim",   # 16
    "teal-dim",       # 17
    "blonde-dim",     # 18
    "blonde-light",   # 19
    "teal-light",     # 20
    "error-light",    # 21
    "text-primary",   # 22
    "text-secondary", # 23
    "text-muted",     # 24
]


def hex_to_rgb(hex_color):
    h = hex_color.lstrip("#")
    if len(h) == 8:
        h = h[:6]
    return tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))


def luminance(r, g, b):
    vals = []
    for x in (r, g, b):
        s = x / 255.0
        vals.append(((s + 0.055) / 1.055) ** 2.4 if s > 0.03928 else s / 12.92)
    return 0.2126 * vals[0] + 0.7152 * vals[1] + 0.0722 * vals[2]


def contrast(rgb1, rgb2):
    l1 = luminance(*rgb1)
    l2 = luminance(*rgb2)
    bright = max(l1, l2)
    dark = min(l1, l2)
    return (bright + 0.05) / (dark + 0.05)


def get_best_text_color(bg_hex, darkest, lightest):
    try:
        bg = hex_to_rgb(bg_hex)
        dk = hex_to_rgb(darkest)
        lt = hex_to_rgb(lightest)
        fb = hex_to_rgb(FALLBACK_BLACK)
        fw = hex_to_rgb(FALLBACK_WHITE)
    except Exception:
        return FALLBACK_WHITE

    max_dark = max(contrast(bg, dk), contrast(bg, fb))
    max_light = max(contrast(bg, lt), contrast(bg, fw))

    if max_light > max_dark:
        return lightest if contrast(bg, lt) >= CONTRAST_THRESHOLD else FALLBACK_WHITE
    else:
        return darkest if contrast(bg, dk) >= CONTRAST_THRESHOLD else FALLBACK_BLACK


def get_palette_extremes(colors):
    valid = []
    for hex_val in colors.values():
        try:
            rgb = hex_to_rgb(hex_val)
            lum = luminance(*rgb)
            valid.append((hex_val, lum))
        except Exception:
            continue
    if not valid:
        return FALLBACK_BLACK, FALLBACK_WHITE
    valid.sort(key=lambda x: x[1])
    return valid[0][0], valid[-1][0]


def parse_scss(scss_path):
    """Parse SCSS $name: #HEX; and $name: $other; declarations."""
    raw = {}
    with open(scss_path, "r") as f:
        for line in f:
            m = re.match(r"\s*\$(\S+)\s*:\s*(.+?)\s*;", line)
            if m:
                raw[m.group(1)] = m.group(2).strip()
    return raw


def resolve_scss(raw):
    """Resolve SCSS aliases ($warning: $blonde) to hex values."""
    resolved = {}
    for name, value in raw.items():
        if value.startswith("#"):
            resolved[name] = value
        elif value.startswith("$"):
            ref = value.lstrip("$")
            if ref in raw and raw[ref].startswith("#"):
                resolved[name] = raw[ref]
    # Add supplemental colors
    for name, hex_val in SUPPLEMENTAL.items():
        if name not in resolved:
            resolved[name] = hex_val
    return resolved


def generate_theme_css(colors, emit_legacy=True):
    darkest, lightest = get_palette_extremes(colors)
    lines = [
        "/* Chrysaki theme — auto-generated by generate_theme_css.py */",
        "/* Source: chrysaki/ags/.config/ags/styles/_palette.scss */",
        "/* Do not edit manually; run generate_and_apply_palette.sh to regenerate */",
        "",
    ]

    # Emit named tokens: @define-color chrysaki-<name> #HEX;
    for name, hex_val in sorted(colors.items()):
        text_color = get_best_text_color(hex_val, darkest, lightest)
        lines.append(f"@define-color chrysaki-{name} {hex_val};")
        lines.append(f"@define-color text-chrysaki-{name} {text_color};")
    lines.append("")

    # Emit legacy indexed aliases
    if emit_legacy:
        lines.append("/* Legacy indexed aliases — remove after full migration */")
        for idx, token_name in enumerate(LEGACY_INDEX_MAP):
            if token_name in colors:
                hex_val = colors[token_name]
                text_color = get_best_text_color(hex_val, darkest, lightest)
                lines.append(f"@define-color color-{idx} {hex_val};")
                lines.append(f"@define-color text-color-{idx} {text_color};")
        lines.append("")

    return "\n".join(lines)


def main():
    scss_path = os.path.expanduser(
        "~/dots/chrysaki/ags/.config/ags/styles/_palette.scss"
    )
    output_path = os.path.expanduser("~/.config/theme/theme.css")

    if len(sys.argv) > 1:
        scss_path = sys.argv[1]
    if len(sys.argv) > 2:
        output_path = sys.argv[2]

    if not os.path.exists(scss_path):
        print(f"Error: {scss_path} not found", file=sys.stderr)
        sys.exit(1)

    raw = parse_scss(scss_path)
    colors = resolve_scss(raw)

    if not colors:
        print("Error: No colors parsed from SCSS", file=sys.stderr)
        sys.exit(1)

    emit_legacy = "--legacy" in sys.argv
    css = generate_theme_css(colors, emit_legacy=emit_legacy)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(css)

    print(f"Generated {output_path} ({len(colors)} colors, legacy={'on' if emit_legacy else 'off'})")


if __name__ == "__main__":
    main()
