#!/usr/bin/env python3
import re
import os
import sys

def hex_to_rgb(hex_color):
    hex_color = hex_color.lstrip('#')
    if len(hex_color) == 3:
        hex_color = ''.join([c*2 for c in hex_color])
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))

def main():
    theme_path = os.path.expanduser("~/.config/theme/theme.css")
    output_path = os.path.expanduser("~/.config/gtk-3.0/gtk.css")

    if not os.path.exists(theme_path):
        print(f"Error: {theme_path} not found")
        return

    with open(theme_path, 'r') as f:
        content = f.read()

    # Parse colors
    colors = {}
    
    # @define-color color-N #HEX;
    matches = re.findall(r'@define-color\s+(color-\d+)\s+(#[0-9a-fA-F]{6,8});', content)
    for name, color in matches:
        colors[name] = color
        
    # @define-color text-color-N #HEX;
    matches_text = re.findall(r'@define-color\s+(text-color-\d+)\s+(#[0-9a-fA-F]{6,8});', content)
    for name, color in matches_text:
        colors[name] = color # Add text colors to the same dict for easy lookup

    if not colors:
        print("No colors found")
        return

    # Mapping logic
    def get_col(name, fallback="#000000"):
        return colors.get(name, fallback)

    # Map theme colors to GTK roles
    # bg_color -> color-0
    # fg_color -> text-color-0
    # base_color -> color-3 (Main view background)
    # text_color -> text-color-3
    # selected_bg_color -> color-2
    # selected_fg_color -> text-color-2
    # tooltip_bg_color -> color-5
    # tooltip_fg_color -> text-color-5
    
    vars = {
        "bg_color": get_col("color-0", "#353535"),
        "fg_color": get_col("text-color-0", "#ffffff"),
        "base_color": get_col("color-3", "#2d2d2d"),
        "text_color": get_col("text-color-3", "#ffffff"),
        "selected_bg_color": get_col("color-2", "#4a90d9"),
        "selected_fg_color": get_col("text-color-2", "#ffffff"),
        "tooltip_bg_color": get_col("color-5", "#000000"),
        "tooltip_fg_color": get_col("text-color-5", "#ffffff"),
    }

    gtk_css_content = f"""/* Generated by update_colors.py */

/* Color Definitions */
@define-color bg_color {vars['bg_color']};
@define-color fg_color {vars['fg_color']};
@define-color base_color {vars['base_color']};
@define-color text_color {vars['text_color']};
@define-color selected_bg_color {vars['selected_bg_color']};
@define-color selected_fg_color {vars['selected_fg_color']};
@define-color tooltip_bg_color {vars['tooltip_bg_color']};
@define-color tooltip_fg_color {vars['tooltip_fg_color']};

/* Apply Colors */
window {{
    background-color: @bg_color;
    color: @fg_color;
    border-color: darker(@bg_color);
}}

/* Views (File Lists, Text Areas) */
view, list, row, entry, textview {{
    background-color: @base_color;
    color: @text_color;
}}

view:selected, list:selected, row:selected {{
    background-color: @selected_bg_color;
    color: @selected_fg_color;
}}

/* Thunar Specifics */
/* Mute the backgrounds by mixing with dark neutral grey to desaturate */
.thunar .sidebar {{
    background-color: mix(@bg_color, #252525, 0.4);
}}

.thunar .view {{
    background-color: mix(@base_color, #202020, 0.4);
}}

.thunar button {{
    padding: 1px 3px;
    /* Very subtle tint of selected color on top of muted background */
    background-color: mix(@selected_bg_color, #303030, 0.15);
    border-color: mix(@selected_bg_color, #303030, 0.3);
    color: @text_color;
}}

.thunar button:hover {{
    background-color: mix(@selected_bg_color, #303030, 0.25);
}}

.thunar button label {{
    color: @text_color;
}}

/* Header Bars / Toolbars */
headerbar, toolbar {{
    background-color: @bg_color;
    color: @fg_color;
}}

/* Buttons */
button {{
    background-color: alpha(@fg_color, 0.1);
    color: @fg_color;
    border-radius: 4px;
    border: 1px solid alpha(@fg_color, 0.2);
}}

button label {{
    color: @fg_color;
}}

button:hover {{
    background-color: alpha(@fg_color, 0.2);
}}

button:active {{
    background-color: @selected_bg_color;
    color: @selected_fg_color;
}}

button:active label {{
    color: @selected_fg_color;
}}

/* Scrollbars */
scrollbar slider {{
    background-color: alpha(@fg_color, 0.2);
    min-width: 8px;
    border-radius: 4px;
}}

scrollbar slider:hover {{
    background-color: alpha(@fg_color, 0.4);
}}
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(gtk_css_content)
    
    print(f"Updated {output_path}")

if __name__ == "__main__":
    main()
