#!/usr/bin/env python3
import re
import os

def main():
    theme_path = os.path.expanduser("~/.config/theme/theme.css")
    output_path = os.path.expanduser("~/.config/gtk-3.0/gtk.css")

    if not os.path.exists(theme_path):
        print(f"Error: {theme_path} not found")
        return

    with open(theme_path, 'r') as f:
        content = f.read()

    colors = {}
    matches = re.findall(r'@define-color\s+((?:chrysaki|text-chrysaki)-[\w-]+)\s+(#[0-9a-fA-F]{6,8});', content)
    for name, color in matches:
        colors[name] = color

    if not colors:
        print("No colors found")
        return

    def get_col(name, fallback="#000000"):
        return colors.get(name, fallback)

    vars = {
        "bg_color": get_col("chrysaki-base", "#353535"),
        "fg_color": get_col("text-chrysaki-base", "#ffffff"),
        "base_color": get_col("chrysaki-raised", "#2d2d2d"),
        "text_color": get_col("text-chrysaki-raised", "#ffffff"),
        "selected_bg_color": get_col("chrysaki-teal", "#197278"),
        "selected_fg_color": get_col("text-chrysaki-teal", "#ffffff"),
        "tooltip_bg_color": get_col("chrysaki-blue", "#000000"),
        "tooltip_fg_color": get_col("text-chrysaki-blue", "#ffffff"),
    }

    gtk_css_content = f"""/* Generated by update_colors.py */

/* Color Definitions */
@define-color bg_color {vars['bg_color']};
@define-color fg_color {vars['fg_color']};
@define-color base_color {vars['base_color']};
@define-color text_color {vars['text_color']};
@define-color selected_bg_color {vars['selected_bg_color']};
@define-color selected_fg_color {vars['selected_fg_color']};
@define-color tooltip_bg_color {vars['tooltip_bg_color']};
@define-color tooltip_fg_color {vars['tooltip_fg_color']};

/* Apply Colors */
window {{
    background-color: @bg_color;
    color: @fg_color;
    border-color: darker(@bg_color);
}}

/* Views (File Lists, Text Areas) */
view, list, row, entry, textview {{
    background-color: @base_color;
    color: @text_color;
}}

view:selected, list:selected, row:selected {{
    background-color: @selected_bg_color;
    color: @selected_fg_color;
}}

/* Thunar Specifics */
/* Mute the backgrounds by mixing with dark neutral grey to desaturate */
.thunar .sidebar {{
    background-color: mix(@bg_color, #252525, 0.4);
}}

.thunar .view {{
    background-color: mix(@base_color, #202020, 0.4);
}}

.thunar button {{
    padding: 1px 3px;
    /* Very subtle tint of selected color on top of muted background */
    background-color: mix(@selected_bg_color, #303030, 0.15);
    border-color: mix(@selected_bg_color, #303030, 0.3);
    color: @text_color;
}}

.thunar button:hover {{
    background-color: mix(@selected_bg_color, #303030, 0.25);
}}

.thunar button label {{
    color: @text_color;
}}

/* Header Bars / Toolbars */
headerbar, toolbar {{
    background-color: @bg_color;
    color: @fg_color;
}}

/* Buttons */
button {{
    background-color: alpha(@fg_color, 0.1);
    color: @fg_color;
    border-radius: 4px;
    border: 1px solid alpha(@fg_color, 0.2);
}}

button label {{
    color: @fg_color;
}}

button:hover {{
    background-color: alpha(@fg_color, 0.2);
}}

button:active {{
    background-color: @selected_bg_color;
    color: @selected_fg_color;
}}

button:active label {{
    color: @selected_fg_color;
}}

/* Scrollbars */
scrollbar slider {{
    background-color: alpha(@fg_color, 0.2);
    min-width: 8px;
    border-radius: 4px;
}}

scrollbar slider:hover {{
    background-color: alpha(@fg_color, 0.4);
}}
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(gtk_css_content)

    print(f"Updated {output_path}")

if __name__ == "__main__":
    main()
