#!/usr/bin/env python3
import re
import os

def main():
    theme_path = os.path.expanduser("~/.config/theme/theme.css")
    output_path = os.path.expanduser("~/.config/ghostty/colors")

    if not os.path.exists(theme_path):
        print(f"Error: {theme_path} not found")
        return

    with open(theme_path, 'r') as f:
        content = f.read()

    colors = {}
    matches = re.findall(r'@define-color\s+(chrysaki-[\w-]+)\s+(#[0-9a-fA-F]{6,8});', content)
    for name, color in matches:
        colors[name] = color

    if not colors:
        print("No colors found in theme.css")
        return

    def get(name, fallback="#000000"):
        return colors.get(f"chrysaki-{name}", fallback)

    output = f"""# Ghostty color theme — Chrysaki palette
# Auto-generated by ghostty/scripts/update_colors.py
# Do not edit manually; run ghostty/scripts/update_colors.py to regenerate

background = {get('base', '#161821')}
foreground = {get('text-primary', '#e0e2ea')}
cursor-color = {get('emerald-light', '#1a8a6a')}
selection-background = {get('elevated', '#2e3142')}
selection-foreground = {get('text-primary', '#e0e2ea')}

# ANSI 16-color palette
palette = 0={get('abyss', '#0f1117')}
palette = 1={get('error', '#8C2F39')}
palette = 2={get('emerald', '#14664e')}
palette = 3={get('blonde-dim', '#C4861C')}
palette = 4={get('blue', '#122858')}
palette = 5={get('amethyst-light', '#583090')}
palette = 6={get('teal', '#197278')}
palette = 7={get('text-secondary', '#a0a4b8')}
palette = 8={get('text-muted', '#6a6e82')}
palette = 9={get('error-light', '#b53f4a')}
palette = 10={get('emerald-light', '#1a8a6a')}
palette = 11={get('blonde-light', '#FCC96A')}
palette = 12={get('cerulean', '#3d95e0')}
palette = 13={get('amethyst-light', '#583090')}
palette = 14={get('teal-light', '#20969c')}
palette = 15={get('text-primary', '#e0e2ea')}
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(output)

    print(f"Updated {output_path}")

if __name__ == "__main__":
    main()
