#!/usr/bin/env python3
import re
import os

def main():
    theme_path = os.path.expanduser("~/.config/theme/theme.css")
    output_path = os.path.expanduser("~/.config/ghostty/colors")

    if not os.path.exists(theme_path):
        print(f"Error: {theme_path} not found")
        return

    with open(theme_path, 'r') as f:
        content = f.read()

    colors = {}
    matches = re.findall(r'@define-color\s+(color-\d+)\s+(#[0-9a-fA-F]{6,8});', content)
    for name, color in matches:
        colors[name] = color

    if not colors:
        print("No colors found in theme.css")
        return

    def get_color(idx, fallback="#000000"):
        return colors.get(f"color-{idx}", fallback)

    # Map Chrysaki indexed colors → Ghostty ANSI 16 palette
    # Indices match the roles defined in palette.css / theme.css
    output = f"""# Ghostty color theme — Chrysaki palette
# Auto-generated by ghostty/scripts/update_colors.py
# Do not edit manually; run generate_and_apply_palette.sh to regenerate

background = {get_color(0, '#161821')}
foreground = {get_color(22, '#e0e2ea')}
cursor-color = {get_color(9, '#1a8a6a')}
selection-background = {get_color(12, '#2e3142')}
selection-foreground = {get_color(22, '#e0e2ea')}

# ANSI 16-color palette
palette = 0={get_color(10, '#0f1117')}
palette = 1={get_color(8, '#8C2F39')}
palette = 2={get_color(3, '#14664e')}
palette = 3={get_color(18, '#C4861C')}
palette = 4={get_color(4, '#FBB13C')}
palette = 5={get_color(7, '#583090')}
palette = 6={get_color(2, '#197278')}
palette = 7={get_color(23, '#a0a4b8')}
palette = 8={get_color(24, '#6a6e82')}
palette = 9=#b53f4a
palette = 10={get_color(9, '#1a8a6a')}
palette = 11={get_color(19, '#FCC96A')}
palette = 12={get_color(20, '#20969c')}
palette = 13={get_color(7, '#583090')}
palette = 14={get_color(20, '#20969c')}
palette = 15={get_color(22, '#e0e2ea')}
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(output)

    print(f"Updated {output_path}")

if __name__ == "__main__":
    main()
