general {
    lock_cmd = pidof hyprlock || $HOME/.config/hypr/scripts/lock.sh
    unlock_cmd = pkill -x hyprlock
}

listener {
    timeout = 300
    command = $HOME/.config/hypr/scripts/lock.sh
}

listener {
    timeout = 300
    on-timeout = $HOME/.config/hypr/scripts/wallpaper.sh
}